name: Checks

on: [push]

jobs:
  test-lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Login in Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db &&
         python manage.py test user.tests.test_user_api && 
         python manage.py test recipe.tests.test_recipe_api &&
         python manage.py test recipe.tests.test_tags_api &&
         python manage.py test recipe.tests.test_recipe_api"

